version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  # backend:
  #   build: backend
  #   ports:
  #     - 21080:80
  #   volumes:
  #     # Re-use local composer cache via host-volume
  #     - ~/.composer-docker/cache:/root/.composer/cache:delegated
  #     # Mount source-code for development
  #     - ./:/app

  mysql:
    image: mysql:5.7
    ports:
      - 3389:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: --max_allowed_packet=64M
    volumes:
      # - "./db:/docker-entrypoint-initdb.d" # this is how we persist an SQL db even when the container stops
      - "./mysql-data:/var/lib/mysql"